New story replace form with with simple form for
mattlindsey/mythographer pull request #17
Opened 2023-11-28 16:43 UTC by acelanoit

## Problem

New Story: replaced the form_with with a simple_form_for.
This fully resolves #8

## Solution

Added gem 'simple_form' in Gemfile.
Updated  code in new.html.erb accordingly.

## Details

Also added one line of code to stories_controller to set the instance variable @mythologies again to ensure the form can be re-rendered properly if submit fails:
@mythologies = Mythology.all

2023-11-28 19:45 UTC, mattlindsey requested changes
Thanks. Works good. 
You can remove the file config/initializers/simple_form_bootstrap.rb since we are using Tailwind for styling, not Bootstrap.  Maybe see if adding this gem is good: https://github.com/tarellel/simple_form-tailwind.

Also, run `bundle exec rubocop` to look for any corrections, then `bundle exec rubocop -A` to correct them.  You can add the simple_form.rb file to the `Exclude:` section of rubocop.yml if you want to leave it as-is.

2023-11-28 20:15 UTC, mattlindsey commented on app/views/stories/new.html.erb
> +      <%= f.submit class: 'border font-bold py-2 px-4 rounded', style: 'display: block;' %>
I think you can just add the 'block' class, but this is probably ok too.

2023-11-29 10:54 UTC, acelanoit commented
Morning! I've made some changes based on your feedback, it looks much cleaner now, only left some inline style in to ensure the 2 input fields are perfectly aligned. Hope it's fine now (:

2023-11-29 13:21 UTC, mattlindsey commented
Hi! Looks good. You just need to run `rubocop` and `rubocop -A` (see above) and add simple_form-tailwind gem (if you want).

2023-11-29 13:24 UTC, mattlindsey commented
Actually `rubocop` is good, so merging now! Thanks

2023-11-29 13:25 UTC, merged